version: '3'

services:
  database:
    container_name: container_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: timeManagerDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: postgres
    restart: always

  backend:
    container_name: container_elixir
    build:
      context: .
    image: image_back
    ports:
      - "4000:4000"
    depends_on:
      - database
    command: sh -c "mix ecto.create && mix ecto.migrate && mix phx.server"
    restart: always

  


volumes:
  postgres_data:
