name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.2'
          otp-version: '26.0'

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: /timeManager/deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: cd timeManager && mix deps.get

      # - name: Run tests
      ##   run: cd timeManager && mix test

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install Vercel CLI
        run: npm install -g vercel

      
      - name: Deploy to Vercel

        run: |
          vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}
          vercel build --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --token=$VERCEL_TOKEN
